### ISSUE TITLE
Cobertura-Report : Issue - Unable to locate Source File. Have you specified the source directory?

### ISSUE THREAD

**Issue by puneethsimha** [cobertura/cobertura#110]
Hi Guys

This is regarding a Cobertura-report issue with Java source files.

My source files are in different packages as follows:

src/package1/package2/Source1.java
src/package3/package4/Source2.java

I'm able to successfully instrument the source files and I'm now trying to generate a Cobertura report using the following build-target in my build.xml : 

<target name = "cobertura-report "depends="release">
   <cobertura-report format = "html"
                                destdir = "/home/puneeth/CC"
                                datafile="/home/puneeth/Cobertura_ser">

  <fileset dir = "/home/puneeth/App/src/package1/package2">
      <include name = "*.java">
  </fileset>

  <fileset dir = "/home/puneeth/App/src/package3/package4">
      <include name = "*.java">
  </fileset>

</target>

When I click on any of my source files in the report, I get this error : Cobertura-Report : Issue - Unable to locate Source File. Have you specified the source directory?

Can you please help with this?

**Comment by RenjunLin** [comment]
hooooo! You solved the same issue for me!
