### ISSUE TITLE
Lexical error at line xxx, column xxx.

### ISSUE THREAD

**Issue by roadnorth** [cobertura/cobertura#111]
if the source include a string "ブログタイトル2", then the lexical error will occur.

Soruce code:

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = {"file:conf/applicationContext.xml"})
public class BatchTest  {
	@Autowired
	JobLauncher jobLauncher;
	
	@Autowired
	JobRepository jobRepository;
	
	@Autowired
	Job exportJob;
	
	@Test
	public void testJob() throws Exception {
		JobLauncherTestUtils jobLauncherTestUtils = new JobLauncherTestUtils();
		jobLauncherTestUtils.setJobLauncher( jobLauncher );
		jobLauncherTestUtils.setJobRepository( jobRepository );
		jobLauncherTestUtils.setJob( exportJob );
		
		String s = "ブログタイトル2";

		JobExecution jobExecution = jobLauncherTestUtils.launchJob();
		Assert.assertEquals(BatchStatus.COMPLETED, jobExecution.getStatus());
	}
}

I am using the version 1.9.4.1. The encoding of source code is utf-8.

**Comment by dennisl** [comment]
Fixed in Cobertura 2.1.1.
