### ISSUE TITLE
Incorrect (it seems) bat and SH files

### ISSUE THREAD

**Issue by phao** [cobertura/cobertura#137]
Hi. I've just went to the web site ( http://cobertura.github.io/cobertura/ ), clicked "Download latest release" and got release 2.0.3.

I am a windows (8.1) user, and noticed that the bat files cobertura-instrument.bat, cobertura-report.bat, cobertura-check.bat and cobertura-merge.bat (all bat files) had strange class path settings. For example, from cobertura-instrument.bat:

java -cp "%COBERTURA_HOME%cobertura.jar;%COBERTURA_HOME%lib\asm-3.3.1.jar;%COBERTURA_HOME%lib\asm-tree-3.3.1.jar;%COBERTURA_HOME%lib\asm-commons-3.3.1.jar;%COBERTURA_HOME%lib\log4j-1.2.9.jar;%COBERTURA_HOME%lib\jakarta-oro-2.0.8.jar" net.sourceforge.cobertura.instrument.Main %CMD_LINE_ARGS%

In the lib folder, there is no asm-3.3.1.jar, but there is an asm-4.1.jar. This jakarta-oro-2.0.8.jar is not there either, and as it seems neither is any other version of is (no file named jakarta-* in there [although there is an oro-2.0.8.jar, so I guess that is what it should be]). It (the class path string in the bat file) also seems to be missing some jar files, like asm-analysis-4.1.jar, oro-2.0.8.jar (is this jakarta-oro?) and asm-util-4.1.jar.

Another issue is that it seems cobertura.jar should be a hard link to cobertura-2.0.3.jar. As the package came, that doesn't seem to be working. By deleting cobertura.jar file and making the link again with mklink here on windows, things seemed to work fine (I used WinRar to extract the tar.gz package, which could be an issue, but hasn't been for me for the past years [not that I've used winrar to extract many tar.gz files]).

Making changes by hand on the bat files solved the problem at least for cobertura-instrument, which is all I've used so far (I am __very__ new to Cobertura, so I'm not really sure if I've fixed anything [I've just downloaded it as recommended by the JUnit in Action book -- I'm minutes new to Cobertura =D]). THe SH files also seem to be with the issue.

**Comment by dennisl** [comment]
Fixed in the Cobertura 2.1.1 release.
