### ISSUE TITLE
Instrumentation fails when there is no base directory

### ISSUE THREAD

**Issue by stevesaliman** [cobertura/cobertura#179]
I'm invoking the InstrumentMain's main class with no base directory and a fully qualified path to a directory with classes to instrument.  This worked fine in version 2.0.3, but is broken in 2.0.4.

I think this is because of changes made to argument processing.

In 2.0.3, the base directory is a string which is initialized to be a null String.  When we create file objects to add to the instrument list, cobertura calls ```new CoberturaFile(baseDir, args[i])```, and with a null base directory, all is well.

In 2.0.4, the base directory is a ```File``` object that is initialized to ```new File(".")```, and files are added with ```new CoberturaFile(getBaseDirectory().getPath(), file)```, which turns ```/path/to/classes``` into ```./path/to/classes```, which doesn't exist.

I think the base directory in ArgumentBuilder (and Arguments) need to revert to a String with no initial value.  If you agree, I can include that fix with the pull request for Issue #175 

Steve

**Comment by dennisl** [comment]
Fixed in the Cobertura 2.1.1 release.
