### ISSUE TITLE
Will Cobertura (or ASM) Support Java 7 with Correct Coverage?

### ISSUE THREAD

**Issue by mecorusfc** [cobertura/cobertura#190]
I have numerous examples (from Groovy and Java) where upgrading to Java 7 causes Cobertura to calculate seriously incorrect coverage amounts (showing half or less of the actual coverage).  I provided some of them in recent issues such as #184   I'm trying to determine if Cobertura has a future.  Is there hope that a future ASM will help or would Cobertura need to be substantially re-written to make it work and calculate correct coverage for Java 7?

Could somebody reply to this and at least say that Cobertura committers are aware of the issue and looking into it (or not)?

**Comment by dennisl** [comment]
Fixed in 2.1.1.

**Comment by mecorusfc** [comment]
We’ll test that out.

Thanks,

Mike
