### ISSUE TITLE
Can we publish the latest snapshot to Maven Central?

### ISSUE THREAD

**Issue by stevesaliman** [cobertura/cobertura#192]
I've seen a several issues lately relating to ASM and coverage levels.  I've gotten a couple in the Gradle Cobertura plugin that also seems related to ASM.  In the case of the Gradle issues, I've noticed that things seem to behave better in version 2.1.

I'm thinking we should upload the latest 2.1 snapshot to the snapshot repository.  If we do, we can have people try it out and let us know if things are better with the 2.1 release.  I've uploaded the latest snapshot of the Gradle plugin, but I'm not authorized to publish Cobertura artifacts.

I was also wanting to time my next Gradle plugin release around the production release of Cobertura 2.1  It seemed like that was right around the corner a little while ago, but I haven't seen anything lately.  Is there a targeted release date?

**Comment by dennisl** [comment]
@christ66 Could you please publish another SNAPSHOT to central? I have finished my work on the Maven plugin for Cobertura, and would like for us to release Cobertura in its current state.

@stevesaliman Have you had time to work on the Gradle plugin for Cobertura?

**Comment by stevesaliman** [comment]
The Gradle plugin is pretty flexible with respect to the version of Cobertura it uses.  Users can use the 2.1 SNAPSHOT now by adding a line to their build.gradle files.  Once the 2.1 release of Cobertura is officially released, I'll make it the default version used by the plugin and release the plugin.
