### ISSUE TITLE
cobertura will not capture the coverage data when using `1.8` for `maven-compiler-plugin`

### ISSUE THREAD

**Issue by Huntter** [cobertura/cobertura#227]
When using `1.8` version for the `<source/>` and `<target/>` property,  cobertura not capture the coverate data when run `mvn site` or `mvn cobertura:cobertura` command.
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>2.3.2</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<encoding>utf-8</encoding>
	</configuration>
</plugin>
```

**Comment by dennisl** [comment]
Please try Cobertura Maven Plugin 2.7, which has just been released, to see is it solves your issue.

**Comment by Huntter** [comment]
Yes, it works. tested with JDK8U40, Cobertura Maven Plugin 2.7, thanks.
