### ISSUE TITLE
ERROR - loadCoverageData

### ISSUE THREAD

**Issue by eliassal** [cobertura/cobertura#229]
Hi, I have downloaded the source code for Gameoflife application and trying to follow the steps indicated in the book that uses this application to show Code coverage in Jenkins + Maven.
I am very new to cobertura, running  mvn clean package cobertura:cobertura, I get a coverage with 0.0 everywhere in spite of the fact that around 50 tests are run. The output is :+1: INFO] --- cobertura-maven-plugin:2.6:cobertura (default-cli) @ gameoflife-web ---
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Report time: 188ms

[ERROR] févr. 24, 2015 3:46:52 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
INFO: Cobertura: Loaded information on 2 classes.

[INFO] Cobertura Report generation was successful.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gameoflife ......................................... SUCCESS [ 13.773 s]
[INFO] gameoflife-build ................................... SUCCESS [  0.703 s]
[INFO] gameoflife-core .................................... SUCCESS [  6.612 s]
[INFO] gameoflife-web ..................................... SUCCESS [ 10.741 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.523 s
[INFO] Finished at: 2015-02-24T15:46:52+01:00
[INFO] Final Memory: 28M/247M
[INFO] ------------------------------------------------------------------------
[Cobertura] Publishing Cobertura coverage report...
Publishing Cobertura coverage results...
Cobertura coverage report found.
Code coverage enforcement failed for the following metrics:
    Packages's stability is 0.0 and set mininum stability is 95.0.
    Methods's stability is 0.0 and set mininum stability is 80.0.
    Lines's stability is 0.0 and set mininum stability is 75.0.
    Conditionals's stability is 0.0 and set mininum stability is 75.0.
Setting Build to unstable.
Build step 'Publish Cobertura Coverage Report' changed build result to UNSTABLE
Recording test results
Publishing Javadoc
Finished: UNSTABLE

I ran the same command in a terminal and getting the same output. 

Thanks for your help

**Comment by dennisl** [comment]
This is a bogus error. It is in reality a log statement using java.util.logging that goes to STDERR byt default, which makes it look like an error when using the Cobertura Maven Plugin.

The logging has been changed and fixed in cobertura 2.1.1.

**Comment by eliassal** [comment]
Thanks, I am using cobertura-maven-plugin 2.6 which seems using cobertura 2.0..3
<coberturaVersion>2.0.3</coberturaVersion> (this is from POM of maven plugin).
Can I force it to use the new version?if yes, how please
Thanks

**Comment by dennisl** [comment]
There will be a release of Cobertura Maven Plugin 2.7 shortly.

**Comment by eliassal** [comment]
Hi dennisl, I am struggling since 1 week with Cobertura to generate metrics for coverage. I almost visited all possible threads to understand what configuration should allow generating coverage. I started by basic scenario as follows:
<groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.6</version>
</plugin>
Then added a configuration section , then pointed to ser file then thenas follows
 <configuration>
         <dataFile>${basedir}/target/cobertura.ser</dataFile>
         <formats>
			<format>xml</format>
        	<format>html</format>
        </formats>
        <instrumentation>
        <includes>
              <include>*.*</include>
            </includes>
         </instrumentation>	
        </configuration>

Nothing is generated after a succesful build and getting Zeors % everywhere. In build output, I am getting always "Data file does not contain instrumentation information for the file BadCategory.java" as follows  

[INFO] Cobertura Report generation was successful.
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file BadCategory.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[cobertura] INFO  [main] net.sourceforge.cobertura.reporting.html.HTMLReport - Data file does not contain instrumentation information for the file GoodTestsCategory.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
Report time: 372ms

Can you please just write down what are min/required tags in order to be able to generate coverage metrics correctly. my test project test hjava files are directly under src default package as follows
<sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>src</testSourceDirectory>
![cobertura](https://cloud.githubusercontent.com/assets/8447864/6426199/9a2cb5ac-bf4f-11e4-8a2f-bc3dcb6afe79.jpg)
Thanks in advance

**Comment by eliassal** [comment]
Here is an image to give a clearer view on the pom
![cobertura_002](https://cloud.githubusercontent.com/assets/8447864/6426270/31a00134-bf53-11e4-958d-ee195cfd4cc8.jpg)

**Comment by eliassal** [comment]
Also, I tried adding
 <instrumentation>
                    <excludes>
                        <exclude>*/*.class</exclude>
                    </excludes>
                </instrumentation>
started getting

[cobertura] WARN  [main] net.sourceforge.cobertura.instrument.CoberturaInstrumenter - Unable to instrument file E:\Salam\Dev\WorkspacesEclipse\pluralsight\ProteinTrackerTests\target\generated-classes\cobertura\HelloJUnitTest.class
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:147)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.instrumentClass(CoberturaInstrumenter.java:121)
	at net.sourceforge.cobertura.instrument.CoberturaInstrumenter.addInstrumentationToSingleClass(CoberturaInstrumenter.java:234)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentationToSingleClass(Main.java:298)
	at net.sourceforge.cobertura.instrument.Main.addInstrumentation(Main.java:307)
	at net.sourceforge.cobertura.instrument.Main.parseArguments(Main.java:399)
	at net.sourceforge.cobertura.instrument.Main.main(Main.java:421)
[cobertura] WARN  [main] net.sourceforge.cobertura.instrument.CoberturaInstrumenter - Unable to instrument file E:\Salam\Dev\WorkspacesEclipse\pluralsight\ProteinTrackerTests\target\generated-classes\cobertura\ParameterizedTests.class
java.lang.IllegalArgumentException

and so on for all other classes

**Comment by dennisl** [comment]
As I said before, you need to use Cobertura 2.1.1 to get rid of the error message. That means that you need to use Cobertura Maven Plugin 2.7. It was released yesterday, so please give it a try.

**Comment by eliassal** [comment]
Dennisl, I changed 2.6 to 2.7, I am getting the same behavior, no code coverage, Zeros are everywhere

[INFO] --- cobertura-maven-plugin:2.7:instrument (default-cli) @ ProteinTrackerTests ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 8 classes.
[INFO] Cobertura: Saved information on 8 classes.
[INFO] Cobertura: Saved information on 8 classes.
........
.......
[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.

[INFO] Cobertura Report generation was successful.
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 8 classes.
[INFO] Data file does not contain instrumentation information for the file BadCategory.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file GoodTestsCategory.java.  Ensure this class was instrumented, and this data file contains the instrumentation information.
Report time: 170ms

[INFO] Cobertura Report generation was successful.

**Comment by dennisl** [comment]
If you look at the log you sent in, there are 2 classes that does not contain any instrumentation information.

Please try to use the Cobertura Maven Plugin completely without any special configuration. It should just work out of the box for most cases.

If that does not work, then we need you to provide a sample project that we can debug.

**Comment by eliassal** [comment]
Again, so many thanks for your prompt response. It is exactly what I am looking for, HOW DO I INSTRUMENT MY Classes, should I do something specific to my test classes? This is my problem it is not instrumenting
I have only this in my POM
 <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
         <configuration>
         <dataFile>${basedir}/target/cobertura.ser</dataFile>
         	<formats>
        		<format>xml</format>
        		<format>html</format>
        	</formats>
        </configuration>
      </plugin>

**Comment by dennisl** [comment]
Remove the entire ```<configuration>``` element and the run this on the command line:
```
mvn cobertura:cobertura
```

**Comment by eliassal** [comment]
I did sir, I have only
 <plugin>
 <groupId>org.codehaus.mojo</groupId>
 <artifactId>cobertura-maven-plugin</artifactId>
 <version>2.7</version>
 </plugin>
Reran , got the EXACT same output in index.html, zeros evrywhere and same "Data file does not contain instrumentation " message 

[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ProteinTrackerTests ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 8 source files to E:\Salam\Dev\WorkspacesEclipse\pluralsight\ProteinTrackerTests\target\classes
[WARNING] /E:/Salam/Dev/WorkspacesEclipse/pluralsight/ProteinTrackerTests/src/TrackingServiceTest.java: E:\Salam\Dev\WorkspacesEcli
pse\pluralsight\ProteinTrackerTests\src\TrackingServiceTest.java uses or overrides a deprecated API.
[WARNING] /E:/Salam/Dev/WorkspacesEclipse/pluralsight/ProteinTrackerTests/src/TrackingServiceTest.java: Recompile with -Xlint:depre
cation for details.
[INFO]
[INFO] --- cobertura-maven-plugin:2.7:instrument (default-cli) @ ProteinTrackerTests ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Saved information on 8 classes.
[INFO] Cobertura: Saved information on 8 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.
.....
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] <<< cobertura-maven-plugin:2.7:cobertura (default-cli) < [cobertura]test @ ProteinTrackerTests <<<
[INFO]
[INFO] --- cobertura-maven-plugin:2.7:cobertura (default-cli) @ ProteinTrackerTests ---
[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 8 classes.
[INFO] Data file does not contain instrumentation information for the file BadCategory.java.  Ensure this class was instrumented, a
nd this data file contains the instrumentation information.
[INFO] Data file does not contain instrumentation information for the file GoodTestsCategory.java.  Ensure this class was instrumen
ted, and this data file contains the instrumentation information.
Report time: 190ms

**Comment by dennisl** [comment]
Hi

It looks like your project does not follow the Maven recommended directory layout. The file ```/E:/Salam/Dev/WorkspacesEclipse/pluralsight/ProteinTrackerTests/src/TrackingServiceTest.java``` should be in a folder called ```src/test/java```.

See: http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

Se really need to see the complete ```pom.xml``` for your project and at least the full directory structure with all file names, or better the full source code including the tests.

**Comment by eliassal** [comment]
Yes, I don²t follow maven conventions. Hereunder the full POM, also the structure (as seen in eclipse) is ProteinTrackerTests
              defaultpackage
                 src
                     BadCategory.java
                     GoodTestsCategory.java

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ProteinTrackerTests</groupId>
  <artifactId>ProteinTrackerTests</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>src</testSourceDirectory>
    <scriptSourceDirectory>src</scriptSourceDirectory>
    <resources>
      <resource>
        <directory>src</directory></resource>
    </resources>
    <testResources>
      <testResource><directory>src</directory>
      </testResource>
    </testResources> 
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
        </configuration>
      </plugin> 
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
  		<groupId>ProteinTracker</groupId>
  		<artifactId>ProteinTracker</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>LATEST</version>	
  	</dependency>
  </dependencies>
  <reporting>
  <plugins>
  	<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
        <configuration>
        	<formats>
        		<format>xml</format>
        		<format>html</format>
        	</formats>
        </configuration> 
      </plugin>
  	</plugins>
  </reporting>
</project>

**Comment by eliassal** [comment]
![cobertura_003](https://cloud.githubusercontent.com/assets/8447864/6467223/1898f82c-c1cd-11e4-8e1e-0e856811064e.jpg)

**Comment by eliassal** [comment]
![cobertura_004](https://cloud.githubusercontent.com/assets/8447864/6467261/57bfc8a0-c1cd-11e4-8d17-b419b72fd702.jpg)
![cobertura_005](https://cloud.githubusercontent.com/assets/8447864/6467263/5f91c4b6-c1cd-11e4-99c2-4ee179b7756b.jpg)

**Comment by eliassal** [comment]
I have put the snapshots as the POM is not being able to be displayed correctly when I paste it here

**Comment by eliassal** [comment]
I will try again to paste it
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ProteinTrackerTests</groupId>
  <artifactId>ProteinTrackerTests</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <testSourceDirectory>src</testSourceDirectory>
    <scriptSourceDirectory>src</scriptSourceDirectory>
    <resources>
      <resource>
        <directory>src</directory></resource>
    </resources>
    <testResources>
      <testResource><directory>src</directory>
      </testResource>
    </testResources> 
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.1</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
        </configuration>
      </plugin> 
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
  	<dependency>
  		<groupId>ProteinTracker</groupId>
  		<artifactId>ProteinTracker</artifactId>
  		<version>0.0.1-SNAPSHOT</version>
  	</dependency>
  	<dependency>
  		<groupId>junit</groupId>
  		<artifactId>junit</artifactId>
  		<version>LATEST</version>	
  	</dependency>
  </dependencies>
  <reporting>
  <plugins>
  	<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
        <configuration>
        	<formats>
        		<format>xml</format>
        		<format>html</format>
        	</formats>
        </configuration> 
      </plugin>
  	</plugins>
  </reporting>
</project>

**Comment by dennisl** [comment]
Please see this page to get the correct formatting done:
https://guides.github.com/features/mastering-markdown/

**Comment by dennisl** [comment]
I don't see any configuration for Maven Surefire Plugin, the plugin that runs unit tests. Since your test source files do not follow the Maven naming conventions I suspect that they are not run at all. I strongly suggest that you follow the Maven convention for project layout and naming. Please paste the full build log.

Docs for Maven Surefire Plugin is here:
http://maven.apache.org/surefire/maven-surefire-plugin/
