### ISSUE TITLE
SLF4J being excluded

### ISSUE THREAD

**Issue by lqbweb** [cobertura/cobertura#233]
I can't get cobertura to work on my build anymore since the release of cobertura 2.1. I get all the time:

15:39:25.915 [DEBUG] [TestEventLogger]     java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
15:39:25.915 [DEBUG] [TestEventLogger]         at net.sourceforge.cobertura.coveragedata.TouchCollector.<clinit>(TouchCollector.java:40)

it seems, that as the result of cobertura 2.1, they have changed all usages of java.util.logging with SLF4J, and I guess this should not be excluded anymore as you do in CoberturaPlugin.groovy. Check this:

https://github.com/cobertura/cobertura/issues/213

**Comment by dennisl** [comment]
There is no version 2.1 of Cobertura. Do you mean version 2.1.1?

What is CoberturaPlugin.groovy? Is that something in the Gradle plugin for Cobertura? If so then please file an issue in their issue tracker.

**Comment by lqbweb** [comment]
Yes, sorry. I confused the github pages. I meant to post this on the cobertura gradle plugin.
