### ISSUE TITLE
coverage-04.dtd is missing the new "complexity" attribute of the "method" tag

### ISSUE THREAD

**Issue by palevi67** [cobertura/cobertura#270]
and I think this is causing problems with some reporting tools (i.e. sonarqube)

**Comment by gslowikowski** [comment]
What is the official location of the DTD file?
- `http://cobertura.sourceforge.net/xml/coverage-04.dtd` referenced in Cobertura sources does not have this attribute.
- `https://raw.githubusercontent.com/cobertura/cobertura/master/cobertura/src/site/htdocs/xml/coverage-04.dtd` (I don't know, where is it on Cobertura site) has it.

What URI should I use in "coverage.xml" files (generated by Scoverage tool)?

**Comment by christ66** [comment]
Sorry about that. I thought it was using the latest version. I fixed the official DTD location to contain the method complexity. The official version is http://cobertura.sourceforge.net/xml/coverage-04.dtd.

```
  <!ELEMENT method (lines)>
  <!ATTLIST method name        CDATA #REQUIRED>
  <!ATTLIST method signature   CDATA #REQUIRED>
  <!ATTLIST method line-rate   CDATA #REQUIRED>
  <!ATTLIST method branch-rate CDATA #REQUIRED>
  <!ATTLIST method complexity  CDATA #REQUIRED>
```
