### ISSUE TITLE
Cobertura to consume JSON file

### ISSUE THREAD

**Issue by RamuRChenchaiah** [cobertura/cobertura#278]
Hi ,

Is there a way to configure Cobertura to consume JSON file?

Thanks, 
Ramu

**Comment by christ66** [comment]
Hi @RamuRChenchaiah,

I'm not sure I understand what you mean by cobertura to consume a JSON file. Cobertura does not consume files other than binaries from the JVM. If you are wondering if Cobertura can report content in a JSON format currently that has not been implemented.
