### ISSUE TITLE
Cannot get coverage for shared jar

### ISSUE THREAD

**Issue by rockytriton** [cobertura/cobertura#297]
I'm trying to use cobertura in maven with a shared project.  I have a main pom that references projects A, B and C.  The project C has shared code which is used by both projects A and B.  Project A and B both have unit tests which test their code as well as code from projects C.  Project C has no unit tests.

I want to be able to run my main pom and have it produce a report which has aggregate results from A, B and C.  The problem is that project C always shows 0% even when I know there is code covered from unit tests in project A and B.

**Comment by christ66** [comment]
Hello @rockytriton ,

Please raise this issue in the cobertura maven project plugin: https://github.com/mojohaus/cobertura-maven-plugin/issues.
