### ISSUE TITLE
Test failed when using Maven to build a jar package from the source

### ISSUE THREAD

**Issue by clarkar** [cobertura/cobertura#304]
I want to use Maven to build a jar package from the source.
When I use "mvn assembly:assembly",there are 4Failure and 1Error tests(in windows 7),so I have to skip the test.
Is this a known issue?

**Comment by AlBundy33** [comment]
I had to skip the tests too - but cobertura seems to work.

**Comment by jmrozanec** [comment]
@clarkar @AlBundy33 Cobertura will work, since by default re-runs the tests. We want to improve this, so that a single run will be required, lowering execution times. A proposal is available at [this fork](https://github.com/jmrozanec/cobertura-chocolate)
