### ISSUE TITLE
XML merging & reporting?

### ISSUE THREAD

**Issue by bootstraponline** [cobertura/cobertura#305]
It looks like there's no way to merge cobertura xml reports or generate HTML reports from them?

**Comment by Balamurugan-R** [comment]
Can  you please explain the use case that you are looking for ?

**Comment by bootstraponline** [comment]
External tools that export to multiple cobertura xml files but are unable to merge or turn them into reports to count total coverage across all projects. For example, slather.

**Comment by christ66** [comment]
@bootstraponline See https://github.com/cobertura/cobertura/wiki/Command-Line-Reference#merging-datafiles.

**Comment by christ66** [comment]
Also there is an ant target for this: https://github.com/cobertura/cobertura/wiki/Ant-Task-Reference#cobertura-merge-task.

**Comment by bootstraponline** [comment]
Yes, I tried both. They don't work on xml. `cobertura.ser` != `cobertura.xml`

There's apparently no way to convert an xmlfile to a datafile.

**Comment by Heeseong** [comment]
i also think cobertura-merge is for .ser that is not for .xml
so i am looking at this https://gist.github.com/tgsoverly/ef975d5b430fbce1eb33

**Comment by merlosy** [comment]
This issue is getting old, but I'll drop this here if it helps.
I made a *node script* to handle the merge and fits my needs:
https://gist.github.com/merlosy/8efabc754985aa6e754a3d5932b1a77d

**Comment by lexdene** [comment]
Is there any way to generate HTML reports from a cobertura `.xml` file without the `.ser` file?
