### ISSUE TITLE
Cobertura maven code coverage report is not accurate

### ISSUE THREAD

**Issue by Balamurugan-R** [cobertura/cobertura#307]
I'm using Cobertura maven plugin for getting the code coverage of testNG/ Selenium scripts.Our code execution flow starts with mvn cobertura:cobertura which will execute the testNG test case internally will run the selenium web driver . when running mvn cobertura:cobetura command in the same directory  sometimes it is not merging the code coverage of the existing run with the new run.It is a blocker for getting our code coverage of our project.

**Comment by Balamurugan-R** [comment]
@christ66 please help out with this issue

**Comment by christ66** [comment]
I'm not sure I understand what you mean by merge the code coverage of the existing run with the new run. I do not believe the maven plugin performs a merge of code coverage as there is no target for merging code coverage sources.

**Comment by Balamurugan-R** [comment]
First run of mvn cobertura:cobertura  executes few TestNG code path and the next run executes few TestNG code path like that we are calling this command for some 500 times. The problem is it capturing code coverage for few test cases and intermittently it is not capturing the coverage for few mvn cobertura:cobertura  and sometimes it is overwriting the files in the target folder (Example : At somepoint of time i have coverage for 50 test cases / 50 mvn cobertura:cobertura in 51st call it is starting from 1st instead of merging with exisiting 50 test cases coverage )

**Comment by Balamurugan-R** [comment]
@christ66 @dennisl @lennartj @jmrozanec   Any pointers for this problem will be really helpful

**Comment by Balamurugan-R** [comment]
Any mailer support for this issue

**Comment by Balamurugan-R** [comment]
closing this issue as i was using Jacoco with sonarqube for my use case .
