### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by vishalmodak** [cobertura/cobertura#310]
Hi..
There have been several commits to the master branch relating to Java8. Will there be a release soon? 
If yes, then any tentative dates?

**Comment by oosterholt** [comment]
+1

**Comment by DougEdey** [comment]
Would love to get Java 8 support, even via `snapshot`, I've tried building locally but there's some test failures :(

**Comment by jmrozanec** [comment]
@vishalmodak @oosterholt @DougEdey @seanf @TheNitek @wvreeven @thomaslee @scotty6435 @njdub @forestbelton @DouglasSweeney we are working on a new release. We also plan jdk8 support but will require help on this! 😄
