### ISSUE TITLE
There's a vulnerability in Jetty which is included with the latest release (2.1.1). 

### ISSUE THREAD

**Issue by Yosief-jitterbit** [cobertura/cobertura#314]
Hi All

There's a vulnerability in Jetty (version 6.1.14) which is included with the latest Cobertura release (2.1.1).
https://www.cvedetails.com/vulnerability-list/vendor_id-9694/product_id-17330/version_id-75934/Mortbay-Jetty-6.1.14.html

I am looking forward  to see it updated in your next release.

Best regards

Yosief Frezghi
Software Engineer 
Jitterbit Inc.

**Comment by christ66** [comment]
@Yosief-jitterbit Cobertura only does integration tests with Jetty and does not build with Jetty. We only use Jetty to make sure that webservers built using cobertura are properly instrumented and coverage data is properly recorded.

Side Note: I thank you for bringing this to my attention, but please make sure to take not disclose security vulnerabilities like this. If you discover a security vulnerability please make sure to contact project maintainers directly. Doing public disclosures like this is considered bad practice and is frowned upon in the security world.

**Comment by Yosief-jitterbit** [comment]
@christ66 : Sure I will do that... thanks for the Side Note
