### ISSUE TITLE
Unit test results

### ISSUE THREAD

**Issue by jagav** [cobertura/cobertura#323]
Folks, 
Just a query:-
Where can I find results /logs of Cobertura unit test executions?

Cheers, 
Jagadeesh Venugopal

**Comment by anupama513** [comment]
Where are you running these testcases? In IDE or any build tool like jenkins?

**Comment by jagav** [comment]
IDE...

**Comment by anupama513** [comment]
If you are using IDE like eclipse, you can find logs in the java console. 
Window-> Show View-> Console.
For the Junit test results, as is you can find in
Window -> Show View -> JUnit
For the Cobertura coverage report, you can run a series of test cases and look for the coverage in 
Window->Show View-> Cobertura-> Coverage Session View.

Hope you are looking for one of these.
