### ISSUE TITLE
Can we define rules for excluding/ignoring files in the coverage reports ?

### ISSUE THREAD

**Issue by manasshukla** [cobertura/cobertura#327]
Hi Team,

Is there a way we can create rules for excluding/ignoring class files from coverage reports ? For example : can I defile somewhere to ignore all the enums in the codecoverage reports or exlude all the pojos from the coverage report ?

I know that presently cobertura supports ignoreTrivial and CoverageIgnore to suppress getters, setters and methods. CoverageIgnore does not work for classes. 

However, providing a mechanism to create rules for coverage reports would be super awesome ?

**Comment by anupama513** [comment]
If you are using a build manager like maven it is pretty easy to ignore those class files from coverage.
In pom.xml, add these lines.
                    <plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>cobertura-maven-plugin</artifactId>
				<configuration>
					<instrumentation>
						<excludes>						
							<exclude>**/Util.class</exclude>
							<exclude>**/<<Class names goes here>>.class</exclude>
						</excludes>
					</instrumentation>
				</configuration>
			</plugin>

Use this is <build> section of pom.xml .
