### ISSUE TITLE
Avoid auxClasspath for instrumentation? 

### ISSUE THREAD

**Issue by AlBundy33** [cobertura/cobertura#338]
This week I've tried to update our "slightly outdated" cobertura 1.9xxx to 2.1.1

But after that I get a lot of NoClassDefFoundErrors (some classes from libraries and some of our own). 

I already found out that setting the auxClasspath seems to paritially fix this issue. 
Currently I didn't get our eclipse rcp application to start - I have to check this later. 

My first try was to include all libraries from our lib dir but since we have also platform-depended libs inthis directory I don't want to use them all. 
But I also don't want configure each library for each project by hand. :-/

So my question is: is there a way to run cobertura as it was with version 1.9 - with this version there was no trouble with ClassNotFoundErrors. 

Al

**Comment by jmrozanec** [comment]
@AlBundy33 we requested QualInsight if they can contribute back the fixes they created. As soon as we get the fix, will merge it to master.

**Comment by jakob-o** [comment]
Hi,

I would like to help but I am not sure where to start. We basically just programmatically resolved the artifact URLs in the maven prohject and created a new classloader aware of these artifacts.

See https://github.com/QualInsight/qualinsight-mojo-cobertura/pull/36

Regards

Jakob

**Comment by AlBundy33** [comment]
not sure if this was fixed but i think we can close this issue after 6 years...
