### ISSUE TITLE
Is this project still alive? 

### ISSUE THREAD

**Issue by AlBundy33** [cobertura/cobertura#339]
We recently tried to update from cobertura 1.9x to 2.1.1 but due to issue #321 we have to use 2.1.2-SNAPSHOT.

Because 2.1.1 was released on march 2015 I'm wondering if this project is still alive.

**Comment by jmrozanec** [comment]
@AlBundy33 coming back to life! Calling anyone interested in it to help us resolve the issues, update to jdk8 and become agile again. We would like to implement features highlighted in [this fork](https://github.com/jmrozanec/cobertura-chocolate) a few years ago. Help is most welcome!

**Comment by EarthCitizen** [comment]
@jmrozanec Prior to Nov 16, it looked that way. But it seems to have suddenly sprung back to life.

**Comment by jmrozanec** [comment]
@EarthCitizen we are gathering everything required to perform a release and provide regular support to this project.

**Comment by EarthCitizen** [comment]
@jmrozanec I tagged the wrong person in my comment. I meant to tag @AlBundy33 . Sorry about that. I also failed to notice that Al's issue was from March :-)
