### ISSUE TITLE
Questions about coverage report

### ISSUE THREAD

**Issue by yezisama** [cobertura/cobertura#340]
Hi ,

I want to use cobertura for generating code coverage and I have some questions.
When I pulish my project to webserver and do some tests then I can use cobertura to get a code coverage report. 
Next time I change some src and restart webserver without doing any tests, then I want to get a code  coverage report which the new src is added and the coverage result of the old src is not cleared.
Can cobertura achieve my requirement?

Regards,
Yezi

**Comment by anupama513** [comment]
Hi,
    When you want to create a report with new src, please make sure that you run the tests. Without running new tests, the old report still lies the same.
