### ISSUE TITLE
java.lang.IllegalArgumentException: INVOKESPECIAL/STATIC on interfaces require ASM 5

### ISSUE THREAD

**Issue by akamble** [cobertura/cobertura#345]
I have java 1.8.0_121 and  2.7 version of cobertura, I have checked the code coverage  by running the  "mvn cobertura:cobertura" .

**Comment by maksimov** [comment]
Seems the same as #303

**Comment by jmrozanec** [comment]
@maksimov thank you for marking this as a duplicate! @akamble we close this as a duplicate and continue tracking the issue at #303 Thanks!
