### ISSUE TITLE
Exclude logback.xml file from jar.

### ISSUE THREAD

**Issue by lisito** [cobertura/cobertura#375]
When include cobertura dependency in a project, its include the logback.xml file which conflicts with the one from client application.

WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/user/.m2/repository/net/sourceforge/cobertura/cobertura/2.1.1/cobertura-2.1.1.jar!/logback.xml]
WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/home/user/app/logback.xml]

**Comment by jmrozanec** [comment]
@lisito thank you for reporting this! Was handled by @msiemczyk in a PR. Best!
