### ISSUE TITLE
Please mark the project as unmaintained.

### ISSUE THREAD

**Issue by xylo** [cobertura/cobertura#382]
Since this project is obviously dead there should be a big warning in the top of the README.md that this project is unmaintained/dead and maybe also an information how it can be revived.

The current state is very irritating for new users.  If they look to the recent changes they see that the last code changes were only 5 months ago.  So they might get the impression that new releases (at least bug fix releases) are still being built.  Since this is not the case since more than 2 years (https://github.com/cobertura/cobertura/pull/299) it's probably the best to warn new users about this fact, so that they don't try to create new pull requests which will never be released anyway.

**Comment by dlehammer** [comment]
Code frequency tells a similar tale :/
![screenshot from 2018-09-07 16-30-46](https://user-images.githubusercontent.com/17439718/45224894-6cdf4480-b2bb-11e8-8fa4-ff55c0b6cb4d.png)

**Comment by xylo** [comment]
Does this mean the project is maintained again?  Can we hope for new releases?

**Comment by jmrozanec** [comment]
@xylo yes, you can hope for them. We just merged all PRs and are syncing with a team who developed support for Java8. Thanks! 😄

**Comment by xylo** [comment]
That's great news.  Thanks a lot!

**Comment by xylo** [comment]
@jmrozanec Is it really necessary to merge all PRs before creating a new release?  The point is that a lot of people are waiting for a new release which fixes bug #299. This merge is nearly 2 years old and since then we are eager for a new release since ATM cobertura is unfortunately not usable with this bug.
