### ISSUE TITLE
Enable dependabot (or a similar service) to keep dependencioes up to date

### ISSUE THREAD

**Issue by cobexer** [cobertura/cobertura#395]
While you are at updating cobertura maybe also enable https://app.dependabot.com (or a similar service) to get notified of dependency updates :)

**Comment by jmrozanec** [comment]
@cobexer thanks! Will enable it! 😄 best!

**Comment by cobexer** [comment]
Also travis builds aren't triggering =/

**Comment by jmrozanec** [comment]
@cobexer yes, we saw that - there are some issues with code coverage on Travis as well. As soon as we finish merging the PRs will head to this issues to get Cobertura back on track.
