### ISSUE TITLE
Jenkins Build failed not publishing cobertura coverage report in java8

### ISSUE THREAD

**Issue by manjugb** [cobertura/cobertura#398]
Steps I followed
------------------
1.Created Maven Junit Project 
2.In Pom xml added cobertura 
3.In jenkins, i added cobertura plugin
4.configure jenkins to get cobertura coverage report
5.In goals clean cobertura:cobertura
6.Finally my junit tests successfully executed
7.At the time of generating report build will be failed.
Operating System:Linux(Ubuntu)
here is the log
-------------------
[INFO] Cobertura Report generation was successful.

[INFO] Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
[INFO] Cobertura: Loaded information on 3 classes.
Report time: 264ms

[INFO] Cobertura Report generation was successful.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.143 s
[INFO] Finished at: 2019-05-16T12:10:27+05:30
[INFO] Final Memory: 27M/203M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data

[JENKINS] Archiving /home/java-testautomation/jenkins/junit5tests/pom.xml to tdd/junittests/0.0.1-SNAPSHOT/junittests-0.0.1-SNAPSHOT.pom
/home/java-testautomation/jenkins/junit5tests/pom.xml is not inside /var/lib/jenkins/workspace/junittests/home/java-testautomation/jenkins/junit5tests/; will archive in a separate pass
channel stopped
[Cobertura] Publishing Cobertura coverage report...

[Cobertura] No coverage results were found using the pattern '' relative to '/var/lib/jenkins/workspace/junittests'.  Did you enter a pattern relative to the correct directory?  Did you generate the XML report(s) for Cobertura?

ERROR: Step ‘Publish Cobertura Coverage Report’ failed: [Cobertura] No coverage results were found using the pattern '' relative to '/var/lib/jenkins/workspace/junittests'.  Did you enter a pattern relative to the correct directory?  Did you generate the XML report(s) for Cobertura?

Finished: FAILURE

**Comment by manjugb** [comment]
I found the solution here like
I generated xml using mvn cobertura:cobertura -Dcobertura.report.format=xml local maven
i copied coverage.xml into '/var/lib/jenkins/workspace/junittests/
[INFO] Cobertura Report generation was successful.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.174 s
[INFO] Finished at: 2019-05-16T12:30:48+05:30
[INFO] Final Memory: 28M/231M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[JENKINS] Archiving /home/java-testautomation/jenkins/junit5tests/pom.xml to tdd/junittests/0.0.1-SNAPSHOT/junittests-0.0.1-SNAPSHOT.pom
/home/java-testautomation/jenkins/junit5tests/pom.xml is not inside /var/lib/jenkins/workspace/junittests/home/java-testautomation/jenkins/junit5tests/; will archive in a separate pass
channel stopped
[Cobertura] Publishing Cobertura coverage report...

[Cobertura] Publishing Cobertura coverage results...

[Cobertura] Cobertura coverage report found.

Publishing Coverage report....
A total of 1 reports were found
Finished: SUCCESS
Please close this issue

**Comment by manjugb** [comment]
I found the solution 
cobertura:cobertura -Dcobertura.report.format=xml using it would generate xml and copied to 
/var/lib/jenkins/workspace/junittests

**Comment by jacquesedom** [comment]
How to copied coverage.xml in /var/lib/jenkins/workspace/junittests?
