### ISSUE TITLE
Module not found error with grails

### ISSUE THREAD

**Issue by cvniru** [cobertura/cobertura#64]
I get the following error when I build my grails project:

Downloading: code-coverage-1.1.8.pom
| Downloading: code-coverage-1.1.8.pom.sha1
:: problems summary ::
:::: WARNINGS
		module not found: org.grails.plugins#data-source;1.0
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/ivy-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/jars/data-source-1.0.zip
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/bundles/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/dist/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/plugins/data-source-1.0.zip
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-data-source/tags/RELEASE_1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://grails.org/plugins/grails-data-source/tags/RELEASE_1.0/grails-data-source-1.0.zip
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/data-source/1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://repo1.maven.org/maven2/org/grails/plugins/data-source/1.0/data-source-1.0.zip
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/data-source/1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://repository.codehaus.org/org/grails/plugins/data-source/1.0/data-source-1.0.zip
		module not found: org.grails.plugins#hibernate;1.3.4
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/ivy-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/jars/hibernate-1.3.4.jar
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/bundles/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/dist/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/plugins/hibernate-1.3.4.jar
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-hibernate/tags/RELEASE_1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://grails.org/plugins/grails-hibernate/tags/RELEASE_1.3.4/grails-hibernate-1.3.4.jar
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://repo1.maven.org/maven2/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.jar
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://repository.codehaus.org/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.jar
		module not found: org.grails.plugins#tomcat;1.3.4
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/ivy-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/jars/tomcat-1.3.4.jar
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/bundles/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/dist/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/plugins/tomcat-1.3.4.jar
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-tomcat/tags/RELEASE_1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://grails.org/plugins/grails-tomcat/tags/RELEASE_1.3.4/grails-tomcat-1.3.4.jar
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://repo1.maven.org/maven2/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.jar
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://repository.codehaus.org/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.jar
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.grails.plugins#data-source;1.0: not found
		:: org.grails.plugins#hibernate;1.3.4: not found
		:: org.grails.plugins#tomcat;1.3.4: not found
		:: org.grails.plugins#code-coverage;1.1.8: java.text.ParseException: inconsistent module descriptor file found in 'http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom': bad organisation: expected='org.grails.plugins' found='cobertura'; bad module name: expected='code-coverage' found='cobertura'; bad revision: expected='1.1.8' found=''; 
		::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
		grailsCentral: bad organisation found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='org.grails.plugins' found='cobertura'
		grailsCentral: bad module name found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='code-coverage found='cobertura'
		grailsCentral: bad revision found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='1.1.8 found=''
| Downloading: code-coverage-1.1.8.pom
| Downloading: code-coverage-1.1.8.pom.sha1
:: problems summary ::
:::: WARNINGS
		module not found: org.grails.plugins#data-source;1.0
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/ivy-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/jars/data-source-1.0.zip
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/data-source/bundles/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/dist/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/data-source-1.0.xml
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/data-source-1.0.zip
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  /Users/niru/Downloads/grails-2.2.4/plugins/data-source-1.0.zip
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-data-source/tags/RELEASE_1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://grails.org/plugins/grails-data-source/tags/RELEASE_1.0/grails-data-source-1.0.zip
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/data-source/1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://repo1.maven.org/maven2/org/grails/plugins/data-source/1.0/data-source-1.0.zip
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/data-source/1.0/data-source-1.0.pom
	  -- artifact org.grails.plugins#data-source;1.0!data-source.zip:
	  http://repository.codehaus.org/org/grails/plugins/data-source/1.0/data-source-1.0.zip
		module not found: org.grails.plugins#hibernate;1.3.4
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/ivy-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/jars/hibernate-1.3.4.jar
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/hibernate/bundles/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/dist/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/hibernate-1.3.4.xml
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/hibernate-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  /Users/niru/Downloads/grails-2.2.4/plugins/hibernate-1.3.4.jar
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-hibernate/tags/RELEASE_1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://grails.org/plugins/grails-hibernate/tags/RELEASE_1.3.4/grails-hibernate-1.3.4.jar
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://repo1.maven.org/maven2/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.jar
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.pom
	  -- artifact org.grails.plugins#hibernate;1.3.4!hibernate.jar:
	  http://repository.codehaus.org/org/grails/plugins/hibernate/1.3.4/hibernate-1.3.4.jar
		module not found: org.grails.plugins#tomcat;1.3.4
	==== grailsPlugins: tried
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/predictivenets-code-a06284f5a86c7a4374d5216a3bfb84a49b4040f8/trunk/predictiveNetworks/lib/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/ivy-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/jars/tomcat-1.3.4.jar
	  /Users/niru/Downloads/grails-2.2.4/lib/org.grails.plugins/tomcat/bundles/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/src/libs/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/src/libs/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/dist/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/dist/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/tomcat-1.3.4.xml
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/.grails/2.2.4/cached-installed-plugins/tomcat-1.3.4.jar
	==== grailsHome: tried
	  /Users/niru/Downloads/grails-2.2.4/plugins/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  /Users/niru/Downloads/grails-2.2.4/plugins/tomcat-1.3.4.jar
	==== grailsCentral: tried
	  http://grails.org/plugins/grails-tomcat/tags/RELEASE_1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://grails.org/plugins/grails-tomcat/tags/RELEASE_1.3.4/grails-tomcat-1.3.4.jar
	==== mavenCentral: tried
	  http://repo1.maven.org/maven2/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://repo1.maven.org/maven2/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.jar
	==== http://repository.codehaus.org: tried
	  http://repository.codehaus.org/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.pom
	  -- artifact org.grails.plugins#tomcat;1.3.4!tomcat.jar:
	  http://repository.codehaus.org/org/grails/plugins/tomcat/1.3.4/tomcat-1.3.4.jar
		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: org.grails.plugins#data-source;1.0: not found
		:: org.grails.plugins#hibernate;1.3.4: not found
		:: org.grails.plugins#tomcat;1.3.4: not found
		:: org.grails.plugins#code-coverage;1.1.8: java.text.ParseException: inconsistent module descriptor file found in 'http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom': bad organisation: expected='org.grails.plugins' found='cobertura'; bad module name: expected='code-coverage' found='cobertura'; bad revision: expected='1.1.8' found=''; 
		::::::::::::::::::::::::::::::::::::::::::::::

:::: ERRORS
		grailsCentral: bad organisation found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='org.grails.plugins' found='cobertura'
		grailsCentral: bad module name found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='code-coverage found='cobertura'
		grailsCentral: bad revision found in http://grails.org/plugins/grails-code-coverage/tags/RELEASE_1_1_8/code-coverage-1.1.8.pom: expected='1.1.8 found=''
| Error Failed to resolve dependencies (Set log level to 'warn' in BuildConfig.groovy for more information):

- org.grails.plugins:data-source:1.0
- org.grails.plugins:hibernate:1.3.4
- org.grails.plugins:tomcat:1.3.4
- org.grails.plugins:code-coverage:1.1.8

**Comment by dennisl** [comment]
This problem is about propertly configuring a grails plugin that uses Cobertura. Please report it to the project maintaining that grails plugin.
