### ISSUE TITLE
configuration 'testRuntime' declares a dependency on configuration 'default' which is not declared in the module descriptor cobertura:2.0.3 

### ISSUE THREAD

**Issue by renjith4** [cobertura/cobertura#85]
Hi,

I was using the gradle-cobertura-plugin from https://github.com/stevesaliman/gradl... to run the cobertura tests from gradle. However, recently I started hitting on the following errors

```

FAILURE: Build failed with an exception.

What went wrong: Could not resolve all dependencies for configuration ':testRuntime'. > Module version misc:myproject:1.0-SNAPSHOT, configuration 'testRuntime' declares a dependency on configuration 'default' which is not declared in the module descriptor for net.sourceforge.cobertura:cobertura:2.0.3

```

and the snippet of configuration which I use is the following

```
<code>
buildscript {  
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "net.saliman:gradle-cobertura-plugin:1.2.0"
    }
}
apply plugin: 'java'
apply plugin: 'cobertura'
cobertura {
    cobertura.coverageIgnoreTrivial = true
    coverageFormats = ['xml', 'html']
    cobertura.coverageExcludes = ['.*DTO.*']
}
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile 'com.h2database:h2:1.3.164'
    testCompile group: 'org', name: 'mockachino', version: '0.6.1', configuration: 'runtime'
}

```

```

apply plugin: 'java'
apply plugin: 'cobertura'

cobertura {
    cobertura.coverageIgnoreTrivial = true
    coverageFormats = ['xml', 'html']
    cobertura.coverageExcludes = ['.*DTO.*']
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    testCompile 'com.h2database:h2:1.3.164'
    testCompile group: 'org', name: 'mockachino', version: '0.6.1', configuration: 'runtime'
}

```

Was there any reason why the default configuration is not present in cobertura any more?

The way I fixed this issue was to add a default configuration to ivy.xml of cobertura in gradle cache. 

```

<ivy-module version="2.0">
  <info organisation="net.sourceforge.cobertura" module="cobertura" revision="2.0.3"/>
  <configurations>
        <conf name="default" visibility="public" description="runtime dependencies can be used with this conf" extends="runtime"/>
        <conf name="runtime" description="Runtime dependencies (they are transitive)"/>
  </configurations>
  <publications>
    <artifact name="cobertura" type="jar"  conf="runtime" ext="jar"/>
  </publications>
  <dependencies>
    <dependency org="asm" name="asm" rev="4.1" />
    <dependency org="log4j" name="log4j" rev="1.2.16" />
  </dependencies>
</ivy-module>

```

I raised the issue in gradle forums (http://forums.gradle.org/gradle/topics/configuration_testruntime_declares_a_dependency_on_configuration_default_which_is_not_declared_in_the_module_descriptor_cobertura_2_0_3?rfm=1) and gradle-cobertura-plugin-forum (https://github.com/stevesaliman/gradle-cobertura-plugin/issues/27) and I was asked to raise it here.

**Comment by dennisl** [comment]
This is an issue in the Gradle plugin. That is a separate project and the issue should be reported in that project's issue tracker.
https://github.com/stevesaliman/gradle-cobertura-plugin

**Comment by stevesaliman** [comment]
I had assumed that this was an issue somewhere in the pom.xml for Cobertura itself since the Gradle plugin has so few dependencies, and Cobertura 2.0.3 had several issues with its libraries.

Is this still an issue with the latest releases of Cobertura and the Gradle plugin?
