### ISSUE TITLE
Parsing Problem - Inside a try-with-resources block declarations with 'final' are not allowed  

### ISSUE THREAD

**Issue by evarga** [cobertura/cobertura#87]
If you have a declaration of a resource inside the try-with-resources Java SE 7 language construction qualified with a 'final' keyword then Cobertura will report a parsing error.

Here is a small code snippet demonstrating the problem. The version below will blow up the Cobertura's parser:

try (
    final Connection databaseConnection = dataSource.getConnection();
) {
    your code here...
} catch (SQLException ex) {
    your exception handler here...
}

However, after removing that 'final' qualifier the code will be properly parsed.

**Comment by dennisl** [comment]
I don't know when it was fixed, but this fix made it into the Cobertura 2.1.1 release.
