### ISSUE TITLE
using cobertura 2.0.3 fails with no coverage - fails in saveCoverageData

### ISSUE THREAD

**Issue by maskbit** [cobertura/cobertura#88]
Cobertura does not report coverage in Sonar for this project. I find the below error in jenkins log.

Using Java7 and Cobertura 2.0.3

[INFO] --- cobertura-maven-plugin:2.6:instrument (default-cli) @ domain-project ---[ERROR] Oct 29, 2013 4:23:53 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler saveCoverageData
INFO: Cobertura: Saved information on 203 classes.

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.

INFO] --- cobertura-maven-plugin:2.6:cobertura (default-cli) @ domain-payment ---
[INFO] Cobertura 2.0.3 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file

[ERROR] Oct 29, 2013 4:37:20 PM net.sourceforge.cobertura.coveragedata.CoverageDataFileHandler loadCoverageData
SEVERE: Cobertura: Error reading file /x/Mobile/projects/domain/domain-project/target/cobertura/cobertura.ser: null
java.io.EOFException

**Comment by pkrishanth** [comment]
I am using jav 8 and had same issue as @grayaii while downgrading

Any luck?

**Comment by dennisl** [comment]
Could someone please try this using Cobertura 2.1.1 or Cobertura Maven Plugin 2.7?

**Comment by ckarawani** [comment]
@dennisl I gave it a try just now. Worked like a charm! :+1:

**Comment by dennisl** [comment]
@ckarawani Thank you for testing!

**Comment by pbshiva** [comment]
I was using cobertura 2.6 with surefire 2.12  when this error poped up, I removed surefire 2.12 still the error pops up, but reports were generated. Probally @parxier @dmehra were doing the same
