### ISSUE TITLE
cobertura.jar vs. cobertura-2.0.3.jar

### ISSUE THREAD

**Issue by timbuethe** [cobertura/cobertura#96]
In the latest version of cobertura, "cobertura.jar" is called "cobertura-2.0.3.jar". In the executables (e.g. cobertura-report.bat), the classpath still contains "cobertura.jar" without version number and therefore fails to start.

In my opinion there are three ways to fix this:
- drop the version number from cobertura.jar again
- change the classpath in the executables to contain the version number (has to be changed in every new release)
- use wildcards in classpath, e.g. "cobertura*.jar", which works only on newer JREs, or let the .bat file create the cp dynamically.

**Comment by dennisl** [comment]
The current solution is to inject the version number into the start scripts, i.e. your bullet 2 but automatically updated.

I've added an enhacement request in #214 to use a plugin for this.
